---
title: "Untitled"
author: "Max Hübner"
date: "9/19/2021"
output: html_document
---


```{r setup, include=FALSE}
library(tidyverse)
library(hubnR)
library(tidytext)

theme_set(theme_hubnr())
```

```{r}
ff_matches <- read_csv("data/ff-matches-2017-2021.csv")
ff_history <- read_csv("data/ff-history-2017-2021.csv")
```

```{r}
ff_history %>% 
  arrange(desc(points)) %>% 
  group_by(pos) %>% 
  group_modify(~ head(.x, 5)) %>%
  mutate(lbl = str_glue("{player}\n{year}-{week} | {points} Pts."),
         lbl = reorder_within(lbl, points, pos),
         year = as.factor(year)) %>% 
  ggplot(aes(points, lbl, fill = pos)) +
  geom_col() +
  scale_y_reordered() + 
  facet_wrap(~pos, scales = "free") + 
  theme(legend.position = "none") +
  labs(title = "Best Fantasy Scores By Position",
       subtitle = "(Only Rostered Players)",
       x = NULL,
       y = NULL,
       caption = "Data: NFL/Sleeper Fantasy\nViz: @HubnerStats")
```

```{r}
ff_history %>% 
  filter(year == 2020) %>% 
  arrange(desc(points)) %>% 
  group_by(pos) %>% 
  group_modify(~ head(.x, 5)) %>%
  mutate(lbl = str_glue("{player}\nWk. {week} | {points} Pts."),
         lbl = reorder_within(lbl, points, pos),
         year = as.factor(year)) %>% 
  ggplot(aes(points, lbl, fill = pos)) +
  geom_col() +
  scale_y_reordered() + 
  facet_wrap(~pos, scales = "free") + 
  theme(legend.position = "none") +
  labs(title = "Best Fantasy Scores By Position - 2020",
       subtitle = "(Only Rostered Players)",
       x = NULL,
       y = NULL,
       caption = "Data: Sleeper Fantasy\nViz: @HubnerStats")
```

```{r}
t_wins <- ff_matches %>% 
  count(year, manager = manager_winner, sort = T, name = "W")

t_loss <- ff_matches %>% 
  count(year, manager = manager_loser, sort = T, name = "L")

total_winloss <- t_wins %>% 
  left_join(t_loss, by = c("year", "manager"))

total_winloss %>% 
  group_by(manager) %>% 
  summarise(W = sum(W),
            L = sum(L),
            exp = n()) %>% 
  ungroup() %>% 
  mutate(games_played = W+L,
         pct_win = scales::percent(W/games_played)) %>% 
  arrange(-(W/games_played))

total_winloss %>% 
  mutate(games_played = W+L,
         pct_win = scales::percent(W/games_played)) %>% 
  arrange(-(W/games_played))
```


```{r}
motw <- c("Bauer", "Marc")
```

```{r}
ff_matches %>% 
  filter(manager_winner %in% motw & manager_loser %in% motw) %>% 
  mutate(diff = score_winner - score_loser)
```


```{r}
ff_history %>% 
  filter(team_manager %in% motw & team_away_manager %in% motw,
         pos != "BN") %>% 
  select(pos:team) %>% 
  filter(year == 2020) %>% 
  View()
```

```{r}
# Loser Picks
ff_history %>% 
  filter(team_manager %in% motw & team_away_manager %in% motw,
         pos != "BN") %>% 
  arrange(points) %>% 
  group_by(pos) %>% 
  group_modify(~ head(.x, 5)) %>%
  mutate(lbl = str_glue("{player}\n{year}-{week} | {points} Pts."),
         lbl = reorder_within(lbl, points, pos)) %>% 
  ggplot(aes(points, lbl, fill = team_manager)) +
  geom_col() +
  facet_wrap(~pos, scales = "free") +
  scale_y_reordered() + 
  labs(title = "Game Of The Week - Loser Picks",
       y = "Player Started",
       x = "Points Scored",
       fill = "Manager")
```

```{r}
# Winner Picks
ff_history %>% 
  filter(team_manager %in% motw & team_away_manager %in% motw,
         pos != "BN") %>% 
  arrange(-points) %>% 
  group_by(pos) %>% 
  group_modify(~ head(.x, 5)) %>%
  mutate(lbl = str_glue("{player}\n{year}-{week} | {points} Pts."),
         lbl = reorder_within(lbl, points, pos)) %>% 
  ggplot(aes(points, lbl, fill = team_manager)) +
  geom_col() +
  facet_wrap(~pos, scales = "free") +
  scale_y_reordered() + 
  labs(title = "Game Of The Week - Winner Picks",
       y = "Player Started",
       x = "Points Scored",
       fill = "Manager")
```

```{r}
ff_history %>% 
  filter(team_manager %in% motw & team_away_manager %in% motw,
         pos != "BN") %>% 
  count(team_manager, player, sort = T)
```

```{r}
ff_history %>% 
  filter(player == "J. Jacobs", year == 2020)
```