---
title: "Create Fantasy Schedule"
author: "Max Hübner"
date: "8/24/2021"
output: html_document
---

```{r}
library(tidyverse)
```

```{r}
schedule_raw <- read_csv("data/scheduletemplate.csv",col_names = F) %>% 
  filter(!is.na(X1))
```

```{r}
schedule <- schedule_raw %>% 
  mutate(week = parse_number(X1)) %>% 
  select(week, X2:X6) %>% 
  pivot_longer(cols = X2:X6, values_to = "matchup") %>% 
  select(-name) %>% 
  mutate(home = str_extract(matchup, "\\d+"),
         away = str_sub(str_extract(matchup, "\\d+\\)"), end = -2))
```


```{r}
schedule_sleeper <- schedule %>% 
  readr::type_convert() %>% 
  mutate(div_home = ifelse(home < 6, 1, 2),
         div_away = ifelse(away < 6, 1, 2),
         home = recode(home,
                       "1" = "Speasy",
                       "2" = "TheRealBauer",
                       "3" = "MKx",
                       "4" = "StumpfIstTrumpf",
                       "5" = "Hammichan",
                       "6" = "Hubner",
                       "7" = "MarkusEXperte",
                       "8" = "AllTimeReadyPat",
                       "9" = "Blitzkoerper85",
                       "10" = "Wolverine88"),
         away = recode(away,
                       "1" = "Speasy",
                       "2" = "TheRealBauer",
                       "3" = "MKx",
                       "4" = "StumpfIstTrumpf",
                       "5" = "Hammichan",
                       "6" = "Hubner",
                       "7" = "MarkusEXperte",
                       "8" = "AllTimeReadyPat",
                       "9" = "Blitzkoerper85",
                       "10" = "Wolverine88"))

```

```{r}
# Testing
schedule_sleeper %>% 
  mutate(divsum = div_home + div_away) %>% 
  group_by(week) %>% 
  summarise(div = sum(divsum))

schedule_sleeper %>% 
  mutate(divsum = div_home + div_away) %>% 
  mutate(game_type = case_when(
    divsum == 2 ~ "Div 1 Matchup",
    divsum == 3 ~ "Crossplay",
    divsum == 4 ~ "Div 2 Matchup"
  )) %>% 
  count(game_type, sort=T)
```

```{r}
schedule_sleeper %>% 
  write_csv("output/ff-sleeper-schedule-2021.csv")
```


